
name: CI/CD 

on:
  push:
  workflow_dispatch:


jobs:
  my_homework:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install the software
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Clone the project
      run: git clone https://github.com/username/repository.git
      
    - name: Download dependencies
      run: pip install -r requirements.txt
      
    - name: Create a project build
      run: python app.py
    
    - name: Run unit tests
      run: python -m unittest
    
    
        
        
    
