
name: CI/CD 

on:
  push:
  workflow_dispatch:


jobs:
  my_homework:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install the software
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Clone the project
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        owner: 'alona-ruda'
        repository: 'HW12'
      
      
    - name: Download dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
    
    - name: Test with pytest
      run: pytest tests.py --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml

    - name: Upload pytest test results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results-${{ matrix.python-version }}
        path: junit/test-results-${{ matrix.python-version }}.xml
      if: ${{ always() }}
        
    
    
        
        
    
